version: '3.2'
services:
  utility:
    container_name: utility
    build:
      context: .
      dockerfile: Dockerfile
    image: utility:latest
    expose:
      - 9180
      - 8180
    ports:
    - 8180:8180
